/**
 * 导入与占位文件修复工具
 *
 * 目标：
 * 1) 修复同一文件内从 `react` 的重复导入（避免 `Identifier 'useContext' has already been declared`）
 * 2) 为缺失的本地模块生成“更贴近导入方式”的占位文件（支持 named exports）
 *
 * 说明：
 * - 这些修复仅用于“预览可运行”的兜底，不替代真实业务实现。
 * - 生成/应用链路稳定后，仍应优先让 AI 输出完整正确的文件。
 */

export interface ParsedImportClause {
  defaultImportName?: string;
  namespaceImportName?: string;
  namedImports: string[];
}

function splitImportList(raw: string): string[] {
  return raw
    .split(',')
    .map(s => s.trim())
    .filter(Boolean);
}

/**
 * 解析 `import ... from 'x'` 中的导入子句（不含 from 和路径）。
 *
 * 支持：
 * - React, { useState, useEffect }
 * - { useState, useEffect as UE }
 * - React
 * - * as ReactNS
 */
export function parseImportClause(clause: string): ParsedImportClause {
  const trimmed = clause.trim();

  const namespaceMatch = trimmed.match(/^\*\s+as\s+([A-Za-z_$][A-Za-z0-9_$]*)$/);
  if (namespaceMatch) {
    return { namespaceImportName: namespaceMatch[1], namedImports: [] };
  }

  const defaultAndNamed = trimmed.match(
    /^([A-Za-z_$][A-Za-z0-9_$]*)\s*,\s*\{([\s\S]*)\}\s*$/
  );
  if (defaultAndNamed) {
    return {
      defaultImportName: defaultAndNamed[1],
      namedImports: splitImportList(defaultAndNamed[2] ?? '')
    };
  }

  const namedOnly = trimmed.match(/^\{([\s\S]*)\}\s*$/);
  if (namedOnly) {
    return { namedImports: splitImportList(namedOnly[1] ?? '') };
  }

  const defaultOnly = trimmed.match(/^([A-Za-z_$][A-Za-z0-9_$]*)$/);
  if (defaultOnly) {
    return { defaultImportName: defaultOnly[1], namedImports: [] };
  }

  return { namedImports: [] };
}

export interface ReactImportMergeResult {
  content: string;
  changed: boolean;
}

/**
 * 合并同一文件内来自 `react` 的导入，避免重复声明同名标识符（如 useContext）。
 */
export function mergeReactImports(content: string): ReactImportMergeResult {
  const lines = content.split('\n');
  const reactImportIndices: number[] = [];

  let defaultImportName: string | undefined;
  const namedImportSet = new Set<string>();
  const namedImportOrder: string[] = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    if (/^\s*import\s+type\b/.test(line)) continue;

    const match = line.match(/^\s*import\s+(.+?)\s+from\s+['"]react['"]\s*;?\s*$/);
    if (!match) continue;

    const clause = match[1]?.trim() ?? '';
    const parsed = parseImportClause(clause);

    // namespace import（* as React）不做合并，避免改变语义
    if (parsed.namespaceImportName) continue;

    reactImportIndices.push(i);

    if (parsed.defaultImportName && !defaultImportName) {
      defaultImportName = parsed.defaultImportName;
    }

    for (const named of parsed.namedImports) {
      if (!namedImportSet.has(named)) {
        namedImportSet.add(named);
        namedImportOrder.push(named);
      }
    }
  }

  if (reactImportIndices.length <= 1) {
    return { content, changed: false };
  }

  const insertionIndex = Math.min(...reactImportIndices);
  const filteredLines = lines.filter((_, idx) => !reactImportIndices.includes(idx));

  const named = namedImportOrder;
  let mergedLine = '';
  if (defaultImportName && named.length > 0) {
    mergedLine = `import ${defaultImportName}, { ${named.join(', ')} } from 'react';`;
  } else if (defaultImportName) {
    mergedLine = `import ${defaultImportName} from 'react';`;
  } else if (named.length > 0) {
    mergedLine = `import { ${named.join(', ')} } from 'react';`;
  }

  // 如果合并结果为空（理论上不该发生），直接返回原文
  if (!mergedLine) return { content, changed: false };

  filteredLines.splice(insertionIndex, 0, mergedLine);

  return { content: filteredLines.join('\n'), changed: true };
}

function toSafeComponentIdentifier(rawName: string): string {
  const cleaned = rawName
    .replace(/\.(jsx|tsx)$/, '')
    .replace(/[^a-zA-Z0-9_]+/g, ' ')
    .trim();

  const parts = cleaned.split(/\s+/).filter(Boolean);
  const pascal = parts.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('');
  const safe = pascal || 'AutoGeneratedComponent';
  return /^[A-Za-z_]/.test(safe) ? safe : `Component${safe}`;
}

export interface MissingImportStubSpec {
  defaultImportName?: string;
  /** 需要兜底提供的 named exports（导入侧使用的导出名，而非本地别名） */
  namedExports?: string[];
}

function normalizeExportName(raw: string): string | null {
  const trimmed = raw.trim().replace(/^type\s+/, '').trim();
  if (!trimmed) return null;

  // `Foo as Bar` → `Foo`
  const parts = trimmed.split(/\s+as\s+/i);
  const exportName = (parts[0] ?? '').trim();
  if (!exportName) return null;

  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(exportName) ? exportName : null;
}

/**
 * 根据缺失文件路径 + 导入方式，生成一个尽量“能跑起来”的占位文件。
 */
export function buildPlaceholderForMissingImport(targetPath: string, spec?: MissingImportStubSpec): string {
  const fileName = targetPath.split('/').pop() || 'Component.jsx';
  const ext = (fileName.split('.').pop() || '').toLowerCase();

  const requestedNamedExports = (spec?.namedExports ?? [])
    .map(normalizeExportName)
    .filter((v): v is string => Boolean(v));

  const uniqueNamedExports: string[] = [];
  const namedExportSet = new Set<string>();
  for (const name of requestedNamedExports) {
    if (!namedExportSet.has(name)) {
      namedExportSet.add(name);
      uniqueNamedExports.push(name);
    }
  }

  if (ext === 'jsx' || ext === 'tsx') {
    const defaultComponentName = toSafeComponentIdentifier(spec?.defaultImportName || fileName);

    const contextExports = uniqueNamedExports.filter(name => name.endsWith('Context'));
    const providerExports = uniqueNamedExports.filter(name => name.endsWith('Provider'));
    const otherExports = uniqueNamedExports.filter(
      name => !contextExports.includes(name) && !providerExports.includes(name)
    );

    const reactNamedImports = new Set<string>();
    if (contextExports.length > 0 || providerExports.length > 0) reactNamedImports.add('createContext');

    const reactImportLine = reactNamedImports.size > 0
      ? `import React, { ${Array.from(reactNamedImports).join(', ')} } from 'react';`
      : `import React from 'react';`;

    const lines: string[] = [
      `/**`,
      ` * 自动补全占位模块：${defaultComponentName}`,
      ` *`,
      ` * 做什么：用于兜底解决“导入了不存在/不完整的本地模块文件”导致的 Vite 编译失败。`,
      ` * 为什么：生成/应用链路中可能出现 import 与落盘文件不一致或漏文件，此处先保证项目可运行。`,
      ` *`,
      ` * 说明：这是占位实现，后续应由生成阶段输出真实逻辑替换。`,
      ` */`,
      ``,
      reactImportLine,
      ``
    ];

    // 先输出 Context exports
    for (const ctxName of contextExports) {
      lines.push(`export const ${ctxName} = createContext(null);`);
    }
    if (contextExports.length > 0) lines.push('');

    // Provider exports：优先使用同前缀 Context（AuthProvider -> AuthContext），否则用第一个 Context
    for (const providerName of providerExports) {
      const guessedContext = providerName.replace(/Provider$/, 'Context');
      const contextName = contextExports.includes(guessedContext)
        ? guessedContext
        : (contextExports[0] ?? null);

      if (contextName) {
        lines.push(`export function ${providerName}({ children }) {`);
        lines.push(`  return (`);
        lines.push(`    <${contextName}.Provider value={{}}>`);
        lines.push(`      {children}`);
        lines.push(`    </${contextName}.Provider>`);
        lines.push(`  );`);
        lines.push(`}`);
      } else {
        // 没有 Context 时，退化为简单组件
        lines.push(`export function ${providerName}() {`);
        lines.push(`  return null;`);
        lines.push(`}`);
      }
      lines.push('');
    }

    // 其他 named exports
    for (const name of otherExports) {
      if (/^[A-Z]/.test(name)) {
        lines.push(`export function ${name}() {`);
        lines.push(`  return null;`);
        lines.push(`}`);
      } else {
        lines.push(`export const ${name} = null;`);
      }
      lines.push('');
    }

    // 只有当导入侧需要 default 时才提供 default，避免与常见 *Context 命名冲突
    if (spec?.defaultImportName) {
      const safeDefaultName = namedExportSet.has(defaultComponentName)
        ? `${defaultComponentName}Placeholder`
        : `${defaultComponentName}Placeholder`;

      lines.push(`export default function ${safeDefaultName}() {`);
      lines.push(`  return null;`);
      lines.push(`}`);
    } else if (uniqueNamedExports.length === 0) {
      lines.push(`export default function ${defaultComponentName}() {`);
      lines.push(`  return null;`);
      lines.push(`}`);
    }

    return `${lines.join('\n')}\n`;
  }

  if (ext === 'js' || ext === 'ts') {
    // JS/TS 占位模块：尽量补齐 named exports，默认导出为 {}
    const lines: string[] = [
      `/**`,
      ` * 自动补全占位模块`,
      ` *`,
      ` * 做什么：用于兜底解决缺失导入导致的构建失败。`,
      ` * 为什么：生成链路可能漏掉某些本地工具模块。`,
      ` */`,
      ``
    ];

    for (const name of uniqueNamedExports) {
      lines.push(`export const ${name} = undefined;`);
    }

    if (spec?.defaultImportName || uniqueNamedExports.length === 0) {
      lines.push(`export default {};`);
    }

    return `${lines.join('\n')}\n`;
  }

  return `/* 自动补全占位文件：${fileName} */\n`;
}

